-- Rules configured by users
create table rules (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  enabled boolean not null default true,
  pool text not null,
  conditions jsonb not null default '[]',
  actions jsonb not null default '[]',
  created_at timestamptz not null default now()
);

alter table rules enable row level security;
create policy "Service full access rules" on rules
  for all using (true) with check (true);

-- Actions generated by the rule engine
create table rule_actions (
  id uuid primary key default gen_random_uuid(),
  rule_id uuid not null references rules(id) on delete cascade,
  rule_name text not null,
  status text not null default 'Pending' check (status in ('Pending', 'Completed', 'Dismissed')),
  trigger_reason text not null,
  suggested_action text not null,
  source text not null default 'live' check (source in ('live', 'simulated')),
  details jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index idx_rule_actions_rule on rule_actions (rule_id);
create index idx_rule_actions_status on rule_actions (status);

alter table rule_actions enable row level security;
create policy "Service full access rule_actions" on rule_actions
  for all using (true) with check (true);
